// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kucjac/cleango/eventsource (interfaces: Cursor)

// Package mockes is a generated GoMock package.
package mockes

import (
	reflect "reflect"

	gomock "github.com/golang/mock/gomock"
	eventsource "github.com/kucjac/cleango/eventsource"
)

// MockCursor is a mock of Cursor interface.
type MockCursor struct {
	ctrl     *gomock.Controller
	recorder *MockCursorMockRecorder
}

// MockCursorMockRecorder is the mock recorder for MockCursor.
type MockCursorMockRecorder struct {
	mock *MockCursor
}

// NewMockCursor creates a new mock instance.
func NewMockCursor(ctrl *gomock.Controller) *MockCursor {
	mock := &MockCursor{ctrl: ctrl}
	mock.recorder = &MockCursorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCursor) EXPECT() *MockCursorMockRecorder {
	return m.recorder
}

// OpenChannel mocks base method.
func (m *MockCursor) OpenChannel() (<-chan *eventsource.CursorAggregate, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "OpenChannel")
	ret0, _ := ret[0].(<-chan *eventsource.CursorAggregate)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// OpenChannel indicates an expected call of OpenChannel.
func (mr *MockCursorMockRecorder) OpenChannel() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "OpenChannel", reflect.TypeOf((*MockCursor)(nil).OpenChannel))
}
