// Code generated by protoc-gen-go. DO NOT EDIT.
// source: errors.proto

package errors

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// Error is the error message that has id, it's code and a detail.
type Error struct {
	Id                   string            `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Code                 uint32            `protobuf:"varint,2,opt,name=code,proto3" json:"code,omitempty"`
	Detail               string            `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	Process              string            `protobuf:"bytes,4,opt,name=process,proto3" json:"process,omitempty"`
	Meta                 map[string]string `protobuf:"bytes,5,rep,name=meta,proto3" json:"meta,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Error) Reset()         { *m = Error{} }
func (m *Error) String() string { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()    {}
func (*Error) Descriptor() ([]byte, []int) {
	return fileDescriptor_24fe73c7f0ddb19c, []int{0}
}

func (m *Error) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Error.Unmarshal(m, b)
}
func (m *Error) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Error.Marshal(b, m, deterministic)
}
func (m *Error) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Error.Merge(m, src)
}
func (m *Error) XXX_Size() int {
	return xxx_messageInfo_Error.Size(m)
}
func (m *Error) XXX_DiscardUnknown() {
	xxx_messageInfo_Error.DiscardUnknown(m)
}

var xxx_messageInfo_Error proto.InternalMessageInfo

func (m *Error) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Error) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *Error) GetDetail() string {
	if m != nil {
		return m.Detail
	}
	return ""
}

func (m *Error) GetProcess() string {
	if m != nil {
		return m.Process
	}
	return ""
}

func (m *Error) GetMeta() map[string]string {
	if m != nil {
		return m.Meta
	}
	return nil
}

func init() {
	proto.RegisterType((*Error)(nil), "errors.Error")
	proto.RegisterMapType((map[string]string)(nil), "errors.Error.MetaEntry")
}

func init() {
	proto.RegisterFile("errors.proto", fileDescriptor_24fe73c7f0ddb19c)
}

var fileDescriptor_24fe73c7f0ddb19c = []byte{
	// 184 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xe2, 0xe2, 0x49, 0x2d, 0x2a, 0xca,
	0x2f, 0x2a, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x83, 0xf0, 0x94, 0x0e, 0x33, 0x72,
	0xb1, 0xba, 0x82, 0x98, 0x42, 0x7c, 0x5c, 0x4c, 0x99, 0x29, 0x12, 0x8c, 0x0a, 0x8c, 0x1a, 0x9c,
	0x41, 0x40, 0x96, 0x90, 0x10, 0x17, 0x4b, 0x72, 0x7e, 0x4a, 0xaa, 0x04, 0x13, 0x50, 0x84, 0x37,
	0x08, 0xcc, 0x16, 0x12, 0xe3, 0x62, 0x4b, 0x49, 0x2d, 0x49, 0xcc, 0xcc, 0x91, 0x60, 0x06, 0xab,
	0x83, 0xf2, 0x84, 0x24, 0xb8, 0xd8, 0x81, 0xc6, 0x26, 0xa7, 0x16, 0x17, 0x4b, 0xb0, 0x80, 0x25,
	0x60, 0x5c, 0x21, 0x6d, 0x2e, 0x96, 0x5c, 0xa0, 0x1a, 0x09, 0x56, 0x05, 0x66, 0x0d, 0x6e, 0x23,
	0x71, 0x3d, 0xa8, 0x23, 0xc0, 0x56, 0xea, 0xf9, 0x02, 0x65, 0x5c, 0xf3, 0x4a, 0x8a, 0x2a, 0x83,
	0xc0, 0x8a, 0xa4, 0xcc, 0xb9, 0x38, 0xe1, 0x42, 0x42, 0x02, 0x5c, 0xcc, 0xd9, 0xa9, 0x95, 0x50,
	0x07, 0x81, 0x98, 0x42, 0x22, 0x5c, 0xac, 0x65, 0x89, 0x39, 0xa5, 0x10, 0x27, 0x71, 0x06, 0x41,
	0x38, 0x56, 0x4c, 0x16, 0x8c, 0x49, 0x6c, 0x60, 0x4f, 0x19, 0x03, 0x02, 0x00, 0x00, 0xff, 0xff,
	0x35, 0xfd, 0x3f, 0x5e, 0xe4, 0x00, 0x00, 0x00,
}
